name: 'Lighthouse Maven Build'
description: 'Build Java projects with Maven for use with Lighthouse'
inputs:
  github-username:
    description: 'GitHub Username'
    required: true
  github-token:
    description: 'GitHub User Token'
    required: true
  command:
    description: 'Type of build to create, e.g. non-release'
    required: true
  mvn-arguments:
    description: 'Additional arguments to pass to the maven command'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/build.sh ${{ inputs.command }} \
          --github-username "${{ inputs.github-username }}" \
          --github-token "${{ inputs.github-token }}" \
          ${{ inputs.mvn-arguments}}
      shell: bash
