name: Lighthouse APIs Maven Non-Release Build
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '17'
    secrets:
      github-username:
        required: true
      github-token:
        required: true

jobs:
  lighthouse-maven:
    name: Lighthouse Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'corretto'
          cache: 'maven'
      - name: Lighthouse maven build
        uses: department-of-veterans-affairs/lighthouse-actions-maven-build@master
        with:
          github-username: ${{ secrets.github-username }}
          github-token: ${{ secrets.github-token }}
          command: non-release
