name: Lighthouse APIs Maven Non-Release Build
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '17'
    secrets:
      BUILD_GITHUB_USERNAME:
        required: true
      BUILD_GITHUB_TOKEN:
        required: true

jobs:
  lighthouse-maven:
    name: Lighthouse Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'corretto'
      - name: Lighthouse maven build
        uses: department-of-veterans-affairs/lighthouse-actions-maven-build@master
        with:
          github-username: ${{ secrets.BUILD_GITHUB_USERNAME }}
          github-token: ${{ secrets.BUILD_GITHUB_TOKEN }}
          command: non-release
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
