name: Lighthouse APIs Maven Release Build
on:
  workflow_call:
    inputs:
      promoter:
        type: string
        required: false
      argocd-application-name:
        type: string
        required: false
      argocd-team-name:
        type: string
        required: false
    secrets:
      BUILD_GITHUB_TOKEN:
        required: false
      DVP_JENKINS_USERNAME:
        required: false
      DVP_JENKINS_TOKEN:
        required: false


jobs:
  jenkins-promotatron:
    runs-on: ubuntu-latest
    if: ${{ inputs.promoter != '' }}
    steps:
      - name: Kick Jenkins Promotion Job
        run: |
          JENKINS_URL='https://tools.health.dev-developer.va.gov/jenkins'
          PROMOTATRON_JOB_PATH='job/department-of-veterans-affairs/job/health-apis-promotatron/job/master'
          REQUEST_PAYLOAD='{"parameter":[{"name":"PROMOTER", "value":"${{ inputs.promoter }}"}]}'
          RESPONSE_PAYLOAD=$(mktemp)
          trap "rm ${RESPONSE_PAYLOAD}" EXIT
          requestBuild() {
            curl --silent \
              --request POST \
              --user "${{ secrets.DVP_JENKINS_USERNAME }}:${{ secrets.DVP_JENKINS_TOKEN }}" \
              --output ${RESPONSE_PAYLOAD} \
              --write-out '%{http_code}' \
              --data-urlencode json="${REQUEST_PAYLOAD}" \
              --location "${JENKINS_URL}/${PROMOTATRON_JOB_PATH}/build"
          }
          # We can't really trust all responses from Jenkins.
          # Sometimes Jenkins responds with an HTML page instead of kicking off a build
          for i in {1..3}
          do
            echo "Requesting promotion (${{ inputs.promoter }}) with Jenkins (attempt ${i})"
            # An error is a terminal condition, nothing else we can do
            if ! RESPONSE_STATUS=$(requestBuild); then break; fi
            if grep -q "DOCTYPE html" ${RESPONSE_PAYLOAD}; then sleep 1; continue; fi
            break;
          done
          cat "${RESPONSE_PAYLOAD}"
          if [ "${RESPONSE_STATUS:-}" != 201 ]
          then
            echo "FAILED TO PROMOTE BUILD (${RESPONSE_STATUS:0:100})"
            exit 1
          fi
          echo "Promotion requested."
          echo "See ${JENKINS_URL}/${PROMOTATRON_JOB_PATH}"
  argocd-promotion:
    runs-on: ubuntu-latest
    if: ${{ inputs.argocd-application-name != '' && inputs.argocd-team-name != '' }}
    steps:
      - name: Upgrade application version in dev
        env:
          APPLICATION_NAME: ${{ inputs.argocd-application-name }}
          ARGOCD_TEAM: ${{ inputs.argocd-team-name }}
          GH_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
        run: |
         gh workflow run \
           --repo department-of-veterans-affairs/${ARGOCD_TEAM}-argocd-applications-vault \
           "Promote Application" \
           --field application="${APPLICATION_NAME}" \
           --field environment="dev"
