name: Lighthouse APIs Maven Release Build
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '17'
      github-username:
        type: string
        required: true
      github-token:
        type: string
        required: true

jobs:
  lighthouse-maven:
    name: Lighthouse Maven Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Next snapshot')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # The standard GITHUB_ACTOR cannot push back to a protected branch.
          # We must checkout with a god-mode user.
          token: ${{ inputs.github-token }}
      - name: Setup Java
        id: setup_java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Lighthouse maven build
        uses: department-of-veterans-affairs/lighthouse-actions-maven-build@master
        env:
          JAVA_VERSION: ${{ steps.setup_java.outputs.version }}
        with:
          github-username: ${{ inputs.github-username }}
          github-token: ${{ inputs.github-token }}
          command: release

  snyk:
    name: Run Snyk Scan
    uses: department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline/.github/workflows/snyk.yml@v4.2.0
    needs: [ lighthouse-maven ]
    with:
      config-file: .github/secrel/maven-config.yml
    secrets: inherit